### ISSUE TITLE
Adding Trackpad to Input List Results in High CPU Usage

### ISSUE THREAD

**Issue by shinzon76** [VorpalBlade/keyboard-backlightd#43] opened 2024-07-13 00:10 UTC
**Describe the bug**
Having followed the instructions for compiling, installing and configuring keyboard-backlightd, adding the trackpad to the list of inputs and starting the systemd unit causes high cpu useage. Only the keyboard, thinkpad events and trackpoint monitoring appear to work as expected.

**To Reproduce**
Steps to reproduce the behaviour:

1. configure keyboard-backlightd to monitor the trackpad via the configuration file
2. start the keyboard-backlightd systemd service
3. observe high cpu usage and stuttering in gnome shell while using trackpad

**Expected behaviour**
While the keyboard backlight turns on when the trackpad is used, I would expect low cpu usage.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**System information (please complete the following information):**
 - Linux distro and version: [e.g. Ubuntu 22.04]
 Fedora 40
 - Device: [e.g. Lenovo Thinkpad P15 Gen1 17"]
 Thnkpad T14 Gen 1 AMD 20UD000CUS
 - Version: [e.g. 0.1.1]
 Latest from github. I'm not seeing a --version flag  or version listed in --help
 - Desktop environment & version: [e.g. KDE Plasma 5.27.1]
 Gnome 46 Wayland
 - Output of `uname -srvmpio`: `<output here>`
Linux 6.9.8-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jul  5 16:20:11 UTC 2024 x86_64 unknown unknown GNU/Linux

- List of devices output by `sudo evtest`:
/dev/input/event0:	Power Button
/dev/input/event1:	Lid Switch
/dev/input/event10:	HD-Audio Generic HDMI/DP,pcm=3
/dev/input/event11:	HD-Audio Generic HDMI/DP,pcm=7
/dev/input/event12:	HD-Audio Generic HDMI/DP,pcm=8
/dev/input/event13:	HD-Audio Generic Mic
/dev/input/event14:	HD-Audio Generic Headphone
/dev/input/event2:	Sleep Button
/dev/input/event3:	Power Button
/dev/input/event4:	AT Translated Set 2 keyboard
/dev/input/event5:	Video Bus
/dev/input/event6:	SynPS/2 Synaptics TouchPad
/dev/input/event7:	TPPS/2 Elan TrackPoint
/dev/input/event8:	PC Speaker
/dev/input/event9:	ThinkPad Extra Buttons

- Output of `ls /sys/class/leds`:

enp2s0f0-0::lan  enp6s0-0::lan  input4::capslock    phy0-led           tpacpi::kbd_backlight  tpacpi::standby
enp2s0f0-1::lan  enp6s0-1::lan  input4::numlock     platform::micmute  tpacpi::lid_logo_dot   tpacpi::thinkvantage
enp2s0f0-2::lan  enp6s0-2::lan  input4::scrolllock  platform::mute     tpacpi::power

- Contents of /etc/conf.d/keyboard-backlightd:
```
# Inputs to monitor.
# Should be on form -i /dev/input/... -i /dev/input/...
#
# See README.md for more info
INPUTS=-i /dev/input/by-path/platform-i8042-serio-0-event-kbd \
       -i /dev/input/by-path/platform-thinkpad_acpi-event \
       -i /dev/input/by-path/platform-i8042-serio-2-event-mouse \  [TRACKPOINT]
       -i /dev/input/by-path/platform-i8042-serio-1-event-mouse [TRACKPAD]
# Path to LED under /sys to control
LED=/sys/class/leds/tpacpi::kbd_backlight

# Default brightness
BRIGHTNESS=2

# Timeout in milliseconds after which to turn off the LED.
TIMEOUT=15000

# Time to wait for files showing up. This is useful during boot to handle
# device nodes not yet being available due to late kernel module loading.
WAIT=15000

# Extra command line flags to pass to keyboard-backlightd
# See --help for a full list (though some overlap with the other settings
# in this file). Of particular interest might be:
# * --no-adaptive-brightness
# * --verbose
FLAGS=

# Set service log level
RUST_LOG=warn
```

**Additional context**
Can provide additional information on request

**Comment by VorpalBlade** [comment] 2024-07-13 06:33
Hi, thanks for the report. I have never tried this configuration, as I only wanted backlight to turn on from keyboard input. I'll have to test this out and see what can be done (hopefully something can be done).

I suspect that part of the issue might be that these input devices inherently produce a lot of events when activated (as opposed to keyboards, which generally produce just key down and key up events). However, other software (such as Wayland or X11) don't get high CPU usage from this.

One question, if you built from git, did you use `cargo build --release`? Or did you use the `Makefile` (which does a release build by default)? The key point I'm driving at here is to make sure you aren't running an unoptimised debug build (such as from plain `cargo build` without flags).

**Comment by VorpalBlade** [comment] 2024-07-13 07:08
Oh this is interesting! I did some profiling and it turns out that reading the current LED brightness is very expensive (and it is being done at every event). Unfortunately this was needed to fix issue #5 on non-Thinkpad hardware if I remember correctly

 I will have to think about how to solve this (and also try to remember how the code works, I haven't really done much with this apart from update dependencies for the last year or so).

**Comment by VorpalBlade** [comment] 2024-07-13 07:56
Turns out it was actually very simple to fix. The read value wasn't ever used. I tagged a new release which should be published shortly. (Though there aren't any Fedora packages, so probably not relevant to you. By the way, contributions for this would be welcome if you are interested, I haven't used a RPM based distro in almost 20 years so I couldn't help you much.).

Please let me know if it solves the problem for you.

**Comment by shinzon76** [comment] 2024-07-13 13:34
> I suspect that part of the issue might be that these input devices inherently produce a lot of events when activated (as opposed to keyboards, which generally produce just key down and key up events). However, other software (such as Wayland or X11) don't get high CPU usage from this.

I suspected the same: the high polling rate of the trackpad is causing issues. Maybe it would be possible to add a delay between polls for actively assuming your software is polling for activity at the same rate the trackpad is?

It's worth noting that i did some tests after I posted the issue and **I noticed that the trackpoint IS experiencing the same behavior**, but just not as pronounced. I notice higher than usual CPU usage and some stutter on heavy operations in Gnome shell. Trackpoint might have a lower polling rate than the trackpad, explaining the difference in severity.

> One question, if you built from git, did you use `cargo build --release`? Or did you use the `Makefile` (which does a release build by default)? The key point I'm driving at here is to make sure you aren't running an unoptimised debug build (such as from plain `cargo build` without flags).

I just ran make and make install. I'm unfamiliar with cargo and rust in general.

> Oh this is interesting! I did some profiling and it turns out that reading the current LED brightness is very expensive _in the kernel_ (and it is being done at every event). Unfortunately this was needed to fix issue #5 on non-Thinkpad hardware if I remember correctly.
> 
> The reason for this being slow in the kernel seems to be that it results in an ACPI call to read the brightness from the hardware. Ouch.
> 
Ah! That makes sense. I will compile the new build, test and report back shortly.

Thanks for looking into this issue for me!

**Comment by shinzon76** [comment] 2024-07-13 13:45
Hmm, that's interesting: I'm still seeing the same behavior with 0.1.10, though it does seemed to have lessened _some_. 

Compiled from source, ran make install, copied my old configuration file that I posted in the original post back over to /usr/local/etc/conf.d, and restarted the systemd service.

Still observing high cpu usage, stuttery movement of the cursor, and stutter/delays in gnome shell when activating the overview, switching windows etc. The severity does seem to have been lessened though.

Copy of the compile output:
$ make
# Let cargo figure out if a build is needed
cargo build --release 
    Updating crates.io index
  Downloaded quote v1.0.36
  Downloaded clap_lex v0.7.1
  Downloaded heck v0.5.0
  Downloaded anstyle v1.0.7
  Downloaded clap_derive v4.5.8
  Downloaded cc v1.1.2
  Downloaded unicode-ident v1.0.12
  Downloaded clap v4.5.9
  Downloaded proc-macro2 v1.0.86
  Downloaded clap_builder v4.5.9
  Downloaded syn v2.0.71
  Downloaded object v0.36.1
  Downloaded 12 crates (1.1 MB) in 0.41s
   Compiling cc v1.1.2
   Compiling libc v0.2.155
   Compiling proc-macro2 v1.0.86
   Compiling unicode-ident v1.0.12
   Compiling pkg-config v0.3.30
   Compiling cfg-if v1.0.0
   Compiling cfg_aliases v0.2.1
   Compiling log v0.4.22
   Compiling adler v1.0.2
   Compiling memchr v2.7.4
   Compiling gimli v0.29.0
   Compiling anstyle v1.0.7
   Compiling rustc-demangle v0.1.24
   Compiling anyhow v1.0.86
   Compiling clap_lex v0.7.1
   Compiling heck v0.5.0
   Compiling bitflags v1.3.2
   Compiling miniz_oxide v0.7.4
   Compiling nix v0.29.0
   Compiling bitflags v2.6.0
   Compiling smallvec v1.13.2
   Compiling clap_builder v4.5.9
   Compiling env_filter v0.1.0
   Compiling env_logger v0.11.3
   Compiling object v0.36.1
   Compiling quote v1.0.36
   Compiling syn v2.0.71
   Compiling backtrace v0.3.73
   Compiling evdev-sys v0.2.5
   Compiling evdev-rs v0.6.1
   Compiling addr2line v0.22.0
   Compiling clap_derive v4.5.8
   Compiling clap v4.5.9
   Compiling keyboard-backlightd v0.1.10 (/home/john/git/keyboard-backlightd)
    Finished `release` profile [optimized] target(s) in 20.77s

**Comment by VorpalBlade** [comment] 2024-07-13 14:05
That's odd, I saw about 20-30% CPU usage before and 2-4% CPU usage when monitoring the trackpad on my T14 after this change.

Obligatory "have you tried turning it off and on again" question: Did you run `sudo systemctl restart keyboard-backlightd.service` after `make install`?

Also a tip for making your log and console output more readable on github, to get a code block you can use:

    ```
    Text that should be in a code block goes here
    That is, use three back-quotes before and after the text.
    ```

**Comment by VorpalBlade** [comment] 2024-07-13 14:15
Looking at the flamegraph on my computer I can see that now most of the remaining time is taken up by writing the brightness. This was far less than reading it was before. Perhaps on your model, writing the brightness is more expensive than on mine?

![flamegraph](https://github.com/user-attachments/assets/052c2e1a-e421-4169-9b9d-90e64ec3e356)

The "obvious" thing here would be to not write the brightness if it is the same as before. This sounds great in theory, but in practise it turns out to be hard to be sure that the current brightness hasn't been changed. On Thinkpads it is just about doable (you have to monitor two files, one for other user space changing the brightness and one for hardware changing it). Many (most?) non Thinkpads / non-Lenovos lack the ability to monitor for hardware changes though. 

Perhaps something time based (assume brightness hasn't changed if less than *n* milliseconds since last read) could work, though I worry about the risk of this going out of sync.

I'll have to think about this.

How familiar are you with programming? I'm wondering if I could meaningfully ask you to capture a flamegraph on your computer. The issue is, it is quite involved (and I don't know exactly what packages you would have to install on Fedora, I know it differs between my Arch Linux systems and the Ubuntu systems I run at work).

**Comment by VorpalBlade** [comment] 2024-07-13 15:03
I have made a branch `feature/avoid_unneeded_writes`, could you perhaps try it out and see if it works for you?

In case you are unfamiliar with git:

```bash
git pull
git checkout feature/avoid_unneeded_writes
```

should get you on the right branch (use `git checkout main` to get back afterwards)

**Comment by shinzon76** [comment] 2024-07-13 15:17
> Looking at the flamegraph on my computer I can see that now most of the remaining time is taken up by writing the brightness. This was far less than reading it was before. Perhaps on your model, writing the brightness is more expensive than on mine?

This is definitely a possibility if this is an issue with AMD thinkpads, a far less common configuration.

> Perhaps something time based (assume brightness hasn't changed if less than _n_ milliseconds since last read) could work, though I worry about the risk of this going out of sync.
> 
> I'll have to think about this.
I have the same reservations about doing anything time based--you may end up missing an event and going out of sync.

> How familiar are you with programming? I'm wondering if I could meaningfully ask you to capture a flamegraph on your computer. The issue is, it is quite involved (and I don't know exactly what packages you would have to install on Fedora, I know it differs between my Arch Linux systems and the Ubuntu systems I run at work).

While I've done a fair bit of programing, my experience is woefully out of date, and I know very little about modern tools. That said, I'd be happy to help you in any way I can.

> I have made a branch `feature/avoid_unneeded_writes`, could you perhaps try it out and see if it works for you?

Alright, I'm set up to use the feature branch.

**Comment by VorpalBlade** [comment] 2024-07-13 16:14
> Alright, I'm set up to use the feature branch

Did it help with the CPU usage?

**Comment by shinzon76** [comment] 2024-07-13 18:20
> > Alright, I'm set up to use the feature branch
> 
> Did it help with the CPU usage?

Apologies i saw the same version number and didn't think there had been any code changes yet.  Just tested it and that does seem to have fixed the issue. The cursor seems _maybe_ a small amount more stuttery than normal but that could just be placebo. I'm not noticing any cpu spikes with touchpad or trackpoint usage. Trackpoint does seem a little more stuttery than movement from the trackpad, but again that could be placebo or something i'm only noticing because im paying attention.

**Comment by VorpalBlade** [comment] 2024-07-13 18:46
I only change version numbers for releases, so that is to be expected. I might look into the ability to have a git commit ID as version number though (would be nice for a bunch of other projects too). 

Since I'm a lot less confident that I managed to fix things now, I didn't tag a new release (or even merge it to main). 

> edit: backlight engagement with trackpad usage seems to be inconsistent with this build. it seemed to work initially but i'm not often seeing it light up the keyboard with either movement physical corner clicks now, even after restarting the service.

Hm...

* Is this only for the trackpad? Not other inputs (especially the keyboard)? (That would be very strange, and most likely a bug in an underlying library.)
* You didn't by chance make install the default config over top and forget to add back your changes? (`make install` is really made for distro packages, where it is expected the package manager will ask you about merging the old and new config.)
* You haven't by any chance figured out how to reproduce this state?
* I have no idea how anything could persist after the service has been restarted (there isn't any persistent state). 

There is a line you could add to your config that causes a lot of info to be printed on stderr. This will of course impact CPU usage, but perhaps it will let us figure out what is going on. 

```
RUST_LOG=debug
```

Add that line and restart the service.

This will print a log entry every time it decides on what action to do. You can see this via `systemctl status keyboard-backlightd`. You could probably also use `journalctl` with the correct arguments, but I'm on my phone at the moment so couldn't tell you what flags. This could allow you to watch in real time I believe. 

I would expect to get a log or two line for every input event (every key up or down, every mouse move on the trackpad, etc). If you don't see a whole lot of log lines when interacting with an input then the program doesn't even see those inputs.

**Comment by shinzon76** [comment] 2024-07-13 22:13
> Hm...
> 
>     * Is this only for the trackpad? Not other inputs (especially the keyboard)? (That would be very strange, and most likely a bug in an underlying library.)

That seems to be the case: trackpoint and keyboard both light the backlight as expected, but using the trackpad will not illuminate it, nor will usage keep the backlight from timing out in this current build.

>     * You didn't by chance make install the default config over top and forget to add back your changes? (`make install` is really made for distro packages, where it is expected the package manager will ask you about merging the old and new config.)
I just double checked, and I found the issue: a errant whitespace was introduced in the config file cause it to fall back to the default configuration (or perhaps just ignore what was after the whitepsace, which was the -i command line for the touchpad). Completely my mistake and I apologize for leading you down the wrong path on that.

As far as I can tell now, everything seems to be functioning as expected. The touchpad is lighting the backlight when used, and I'm no longer seeing the massive spike in cpu or lag in gnome shell. I can reproduce the stutter in the trackpoint both with and without the service running, so that must not be related to your code.

**Comment by VorpalBlade** [comment] 2024-07-14 06:41
The branch has been merged into main (please switch back to that) and a new release has been made. Thank you for finding this issue.

**Closed by VorpalBlade** 2024-07-14 06:41 UTC

**Comment by shinzon76** [comment] 2024-07-14 14:25
> The branch has been merged into main (please switch back to that) and a new release has been made. Thank you for finding this issue.

I switched back to main, installed 0.1.11 and can confirm the issue still appears to be fixed. Thank you very much for working on this with me, and for developing this application.
