### ISSUE TITLE
Error when executing the script

### ISSUE THREAD

**Issue by Martin1134** [VorpalBlade/keyboard-backlightd#5] opened 2023-04-23 22:17 UTC
keyboard-backlightd -v --timeout 10000 --led /sys/class/leds/:white:kbd_backlight -i /dev/input/by-path/pci-0000:e6:00.1-usb-0:5:1.1-event-kbd 

Error: ParseIntError { kind: PosOverflow }

**Comment by VorpalBlade** [comment] 2023-04-24 07:46
Hm, I'm not sure what that is. Error reporting is lacking at the moment, it is something I plan to work on. I also cannot reproduce it locally.

I cannot reproduce it with my own setup, so my guess is that there is something in either the LED or the keyboard that throws it off.

* You could test a different input device and see if the issue persists, if so it is likely due to the LED.
* What does this output?
```
cat /sys/class/leds/:white:kbd_backlight/max_brightness
cat /sys/class/leds/:white:kbd_backlight/brightness
```

**Comment by VorpalBlade** [comment] 2023-04-24 08:48
It is probable that commit 87796abe has fixed this. I would still like to know what the value for `max_brightness` is on your system though.

I would appreciate if you can test the latest git version to see if the issue is resolved for you.

**Comment by Martin1134** [comment] 2023-04-24 09:08
Max Brightness is: 

![Bildschirmfoto vom 2023-04-24 11-06-10](https://user-images.githubusercontent.com/44879342/233951546-af347692-aef9-450d-afee-018664187a3c.png)

I will test this ASAP

**Comment by Martin1134** [comment] 2023-04-24 09:16
Script gets stuck now.
![Bildschirmfoto vom 2023-04-24 11-16-27](https://user-images.githubusercontent.com/44879342/233953808-e88c256c-815a-4e1a-841b-fe58a0cefd5f.png)

**Comment by VorpalBlade** [comment] 2023-04-24 09:41
I don't think the program is stuck, just idling in the background doing it's job. If you run the program with `-v` you should see it print some lines such as the following when you type on your keyboard and then let it idle:

```
[DEBUG keyboard_backlightd::policy] State: State { last_input: Instant { tv_sec: 222269, tv_nsec: 333483256 }, keep: None, cur_brightness: 1, requested_brightness: 1 }
[DEBUG keyboard_backlightd::policy] Actions: [SetLed(0), Sleep(None)]
```

This is normal, the program is not a one-time script, but a background daemon.

**Comment by Martin1134** [comment] 2023-04-24 09:45
Ahh you're right. And it works! but if try to start the daemon, that's the output. 

![Bildschirmfoto vom 2023-04-24 11-44-31](https://user-images.githubusercontent.com/44879342/233961026-944968cd-f4cc-41a4-8ea9-c21cd0586724.png)

**Comment by Martin1134** [comment] 2023-04-24 09:49
I think I see the issue `Apr 24 00:26:09 Arch-MBP keyboard-backlightd[36588]: Error: NoSuchFile { path: "/dev/input/by-path/platform-i8042-serio-0-event-kbd" }
`
But where is this coming from?  

![Bildschirmfoto vom 2023-04-24 11-48-50](https://user-images.githubusercontent.com/44879342/233962089-dba9c8b4-f5aa-4194-8f5c-b2ae8092fc2e.png)

**Comment by VorpalBlade** [comment] 2023-04-24 09:51
Ah, I believe you didn't edit `/etc/conf.d/keyboard-backlightd` to remove the example command line parameters and add your own.

**Comment by VorpalBlade** [comment] 2023-04-24 09:53
Oops, you are right. Need to fix that, yes.

**Comment by VorpalBlade** [comment] 2023-04-24 09:58
Let me know if everything works as expected now, and I'll make a new release.

**Comment by Martin1134** [comment] 2023-04-24 10:02
It is working now thank you! But is there any way to not use Default Brightness? So the Brightness goes back to the value before idle?

**Comment by VorpalBlade** [comment] 2023-04-24 10:04
Hm, not sure what you mean? I don't have a keyboard with as many brightness levels as you do, but when I adjust the brightness using Fn+Space I can switch between two levels. I read those in the daemon and remember them. This depends on the existance of `/sys/class/leds/<led name>/brightness_hw_changed`. Does your system not have that file? If so, I will have to think of an alternative solution.

**Comment by Martin1134** [comment] 2023-04-24 10:08
No there is no such file. I suppose that's the reason why it don't work? I'm running a MacBook Pro, so I have like 20 Brightness settings to work with. But that's an issue I can live with for now :)

**Comment by VorpalBlade** [comment] 2023-04-24 10:13
One option would be to have a brightness level in the config file. This would make it impossible to adjust at runtime though.

I could also perhaps read `/sys/class/leds/<led name>/brightness` every time I write to it and remember what the last non-zero value was. The issue here is that I cannot monitor this file for activity and read it when it has changed (at least that doesn't work on a Thinkpad). Could you install `inotify-tools` and try:

```
sudo systemctl stop keyboard-backlightd
sudo inotifywait -m /sys/class/leds/:white:kbd_backlight/brightness
```
Then change the brightness (using whatever method you normally use, like Fn-keycombo or however macs do it) and report the output. 

Note: that command will run indefinitely, so cancel it with Ctrl-c afterwads.

**Comment by Martin1134** [comment] 2023-04-24 10:16
Sure there is the output.

![Bildschirmfoto vom 2023-04-24 12-16-00](https://user-images.githubusercontent.com/44879342/233968217-54267459-2333-4b76-8ae7-aaf7dfa1c791.png)

**Comment by Martin1134** [comment] 2023-04-24 10:21
Great to hear! Let me know if I can contribute to this anyhow!

**Comment by VorpalBlade** [comment] 2023-04-24 10:35
> Great to hear! Let me know if I can contribute to this anyhow!

I will need your help with testing this eventually, but until then I don't believe so.

**Comment by VorpalBlade** [comment] 2023-04-24 11:06
Commit edc02b81 might work for this. In some limited testing on my own Thinkpad it appears to work.

There is one caveat though: with the hardware monitoring approach it is possible to detect that you as a user set the backlight to be completely off, that doesn't work with the alternative approach. It will instead remember the last non-zero value when the daemon sets the value to zero. (It turned out to not be feasible to only monitor for other programs changing the file.)

**Comment by Martin1134** [comment] 2023-04-24 11:14
It works, but yes it behaves as you describe it. I can't really set it  to stay completely off, it always turns on to the last set value.

**Comment by VorpalBlade** [comment] 2023-04-24 11:19
That is as good as it is going to get for laptops without hardware monitoring for now. To handle that final case of turning off the backlight I would need to do a significant rewrite as a full on state machine (something I'm not currently planning to do).

**Comment by VorpalBlade** [comment] 2023-04-24 11:23
Closing as resolved.

**Closed by VorpalBlade** 2023-04-24 11:23 UTC
